# Generated by Django 4.0.5 on 2022-08-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_rename_addr_contacts_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='Inquiry',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
